# Léxico Político Brasileiro - Contexto Bolsonaro (2019-2023)
# Este arquivo contém termos e expressões específicas do contexto político brasileiro

brazilian_political_lexicon:
  
  # Governo Bolsonaro e apoiadores
  governo_bolsonaro:
    - "presidente"
    - "capitão"
    - "mito"
    - "bolsonaro"
    - "jair"
    - "messias"
    - "patriota"
    - "conservador"
    - "direita"
    - "família tradicional"
    - "deus pátria família"
    - "brasil acima de tudo"
    
  # Oposição política
  oposição:
    - "lula"
    - "pt"
    - "petista"
    - "esquerda"
    - "comunista"
    - "socialista"
    - "vermelho"
    - "esquerdista"
    - "bolivariano"
    - "foro de são paulo"
    - "partido dos trabalhadores"
    
  # Instituições
  instituições:
    - "stf"
    - "supremo tribunal federal"
    - "tse"
    - "tribunal superior eleitoral"
    - "congresso"
    - "senado"
    - "câmara"
    - "deputados"
    - "senadores"
    - "ministério"
    - "governo federal"
    - "união"
    - "poderes"
    
  # Teorias conspiratórias
  teorias_conspiração:
    - "urna fraudada"
    - "fraude eleitoral"
    - "ditadura stf"
    - "globalismo"
    - "nova ordem mundial"
    - "deep state"
    - "estado profundo"
    - "illuminati"
    - "maçonaria"
    - "elite globalista"
    - "kit gay"
    - "mamadeira de piroca"
    - "comunismo na educação"
    - "doutrinação"
    - "marxismo cultural"
    
  # Negacionismo sanitário
  saúde_negacionismo:
    - "tratamento precoce"
    - "ivermectina"
    - "cloroquina"
    - "hidroxicloroquina"
    - "ditadura sanitária"
    - "lockdown"
    - "isolamento social"
    - "passaporte sanitário"
    - "vacina experimental"
    - "covid laboratório"
    - "gripezinha"
    - "histeria coletiva"
    - "plandemia"
    - "grande reset"
    
  # Militarismo
  militarismo:
    - "forças armadas"
    - "militares"
    - "intervenção militar"
    - "quartel"
    - "exército"
    - "marinha"
    - "aeronáutica"
    - "comandos militares"
    - "generais"
    - "coronéis"
    - "oficiais"
    - "caserna"
    - "disciplina militar"
    - "ordem e progresso"
    - "ai-5"
    - "ditadura militar"
    - "regime militar"
    
  # Mídia e comunicação
  mídia_comunicação:
    - "fake news"
    - "mídia golpista"
    - "grande mídia"
    - "globo"
    - "rede globo"
    - "folha"
    - "estadão"
    - "veja"
    - "manipulação"
    - "censura"
    - "verdade"
    - "imprensa marrom"
    - "jornalismo"
    - "desinformação"
    
  # Mobilização e ação
  mobilização:
    - "acordem"
    - "despertem"
    - "brasil acorda"
    - "patriotas"
    - "manifestação"
    - "protesto"
    - "passeata"
    - "ato público"
    - "caminhoneiros"
    - "produtores rurais"
    - "empresários"
    - "classe média"
    - "povo brasileiro"
    - "nação"
    
  # Economia e política
  economia_política:
    - "auxílio emergencial"
    - "pix"
    - "marco temporal"
    - "agronegócio"
    - "ruralistas"
    - "mst"
    - "reforma agrária"
    - "terra"
    - "propriedade privada"
    - "livre mercado"
    - "privatização"
    - "estado mínimo"
    - "neoliberalismo"
    
  # Religião e valores
  religião_valores:
    - "cristão"
    - "evangélico"
    - "católico"
    - "pastor"
    - "igreja"
    - "deus"
    - "jesus"
    - "família"
    - "moral"
    - "ética"
    - "valores cristãos"
    - "tradição"
    - "conservadorismo"
    - "aborto"
    - "ideologia de gênero"
    - "lgbt"
    
  # Eleições e democracia
  eleições_democracia:
    - "urna eletrônica"
    - "voto impresso"
    - "auditoria"
    - "transparência"
    - "democracia"
    - "eleições limpas"
    - "soberania popular"
    - "legitimidade"
    - "golpe"
    - "impeachment"
    - "cassação"
    - "mandato"
    
  # Indicadores emocionais
  indicadores_emocionais:
    raiva:
      - "indignação"
      - "revolta"
      - "ódio"
      - "raiva"
      - "injustiça"
      - "absurdo"
      - "inadmissível"
    
    medo:
      - "perigo"
      - "ameaça"
      - "risco"
      - "cuidado"
      - "alerta"
      - "preocupação"
      - "medo"
    
    esperança:
      - "mudança"
      - "futuro"
      - "esperança"
      - "fé"
      - "confiança"
      - "otimismo"
      - "vitória"
    
    urgência:
      - "agora"
      - "urgente"
      - "rápido"
      - "imediato"
      - "já"
      - "hoje"
      - "amanhã pode ser tarde"

# Configurações de análise
analysis_config:
  min_term_frequency: 2
  case_sensitive: false
  include_partial_matches: true
  weight_by_category: true
  
  # Pesos por categoria para scoring
  category_weights:
    governo_bolsonaro: 1.0
    oposição: 1.0
    teorias_conspiração: 1.5
    saúde_negacionismo: 1.5
    militarismo: 1.3
    mobilização: 1.2
    indicadores_emocionais: 0.8