'# Enhanced Model Configuration':
  info: Stage-specific model configurations are loaded from enhanced_model_settings.yaml
  priority: enhanced_config > settings.yaml > environment variables
  supported_stages:
  - political_analysis
  - sentiment_analysis
  - network_analysis
  - qualitative_analysis
  - pipeline_review
  - topic_interpretation
  - validation
anthropic:
  cost_monitoring: true
  enhanced_config_enabled: true
  enhanced_config_path: config/enhanced_model_settings.yaml
  fallback_enabled: true
  max_tokens: 4000
  model: claude-3-5-sonnet-20241022
  temperature: 0.3
cache:
  embedding_cache:
    compression_level: 6
    max_memory_mb: 256
    ttl_hours: 24
  search_cache:
    compression_level: 6
    max_memory_mb: 128
    ttl_hours: 6
clustering:
  method: kmeans
  n_clusters: 10
  use_anthropic_validation: true
  validation_method: semantic
data_validation:
  use_anthropic: false
  validation_level: comprehensive
deduplication:
  semantic_analysis: true
  similarity_threshold: 0.9
  text_column: texto
  use_anthropic: true
domain_analysis:
  batch_size: 30
  credibility_analysis: true
  min_frequency: 5
  use_anthropic: true
embeddings:
  batch_size: 128
  cache_embeddings: true
  integration:
    clustering: true
    deduplication: true
    tfidf_analysis: true
    topic_modeling: true
  max_tokens: 32000
  model: voyage-3.5-lite
  similarity_threshold: 0.8
encoding_fix:
  columns_to_fix:
  - texto
  - text_cleaned
  - canal
  - hashtags
  confidence_threshold: 0.8
  use_anthropic: true
enhanced_models:
  config_file: config/enhanced_model_settings.yaml
  enabled: true
  fallback_to_default: true
  stage_specific_configs: true
feature_extraction:
  extract_emotional_features: true
  extract_political_features: true
  use_anthropic: true
feature_validation:
  enrich_basic: true
  use_anthropic: false
  validate_existing: true
hashtag_normalization:
  min_frequency: 5
  semantic_clustering: true
  similarity_threshold: 0.8
  use_anthropic: true
hybrid_search:
  dense_weight: 0.7
  faiss:
    index_type: IVF
    nlist: 100
    nprobe: 10
  max_results: 100
  min_similarity: 0.1
  rerank_top_k: 200
  sparse_weight: 0.3
  tfidf:
    max_df: 0.95
    max_features: 10000
    min_df: 2
    ngram_range:
    - 1
    - 2
lda:
  alpha: 0.01
  beta: 0.01
  iterations: 1000
  n_topics: 15
  use_anthropic_interpretation: true
logging:
  date_format: '%Y-%m-%d %H:%M:%S'
  default_level: INFO
  file_rotation: 30
  format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  log_to_console: true
  log_to_file: true
network_analysis:
  community_sample_size: 100
  max_nodes: 500
  min_edge_weight: 3
  use_anthropic: true
paths:
  data: data
  documentation: documentation
  logs: logs
  models: models
  processed: data/processed
  raw: data/raw
  results: results
pipeline:
  checkpoint_enabled: true
  stop_on_error: true
pipeline_review:
  detail_level: comprehensive
  generate_recommendations: true
  quality_threshold: 0.8
  use_anthropic: true
political_analysis:
  batch_size: 10
  confidence_threshold: 0.7
  use_anthropic: true
  use_cache: true
processing:
  cache_dir: data/interim/cache
  cache_enabled: true
  chunk_size: 10000
  encoding: utf-8
  max_workers: 4
  memory_limit: 2GB
  sample_size: 10000
  timeout: 3600
project:
  description: 'Análise de Discurso em Canais do Telegram: Bolsonarismo, Negacionismo
    e Autoritarismo'
  model_config_version: 4.9.8
  name: dataanalysis-bolsonarismo
  version: 4.9.8
qualitative:
  confidence_threshold: 0.8
  conspiracy_detection: true
  negacionism_detection: true
  use_anthropic_classification: true
semantic_search:
  cluster_eps: 0.3
  enable_caching: true
  max_results: 100
  min_cluster_size: 5
  similarity_threshold: 0.7
sentiment:
  language: pt
  method: hybrid
  political_context: true
  text_column: text_cleaned
  use_anthropic: true
temporal_analysis:
  analysis_window_days: 7
  event_sensitivity: 0.8
  significance_threshold: 2.0
  use_anthropic: true
text_cleaning:
  preserve_context: true
  remove_emojis: false
  remove_urls: false
  text_column: texto
  use_anthropic: true
tfidf:
  max_features: 5000
  ngram_range:
  - 1
  - 3
  semantic_grouping: true
  use_anthropic: true
